# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
