# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170626_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True, default='2007-01-01 00:00'),
            preserve_default=False,
        ),
    ]
