# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20170627_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.get_image_path),
        ),
    ]
