# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170627_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
    ]
